---
- hosts: srvwin19
  vars:
    ansible_site_path: "c:\\inetpub\\wwwroot\\ansibletest"
    staging_path: "c:\\deploy"
    ansible_test_staging_path: "{{ staging_path }}\\ansible-test-site-{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
  tasks:
  - name: Preparando instalacao do IIS
    win_feature:
      name: "Web-Server"
      state: present
      restart: no
      include_sub_features: yes
      include_management_tools: no
  - name: Finalizando instalacao do IIS
    win_file: path={{ staging_path }} state=directory

  - name: Criando index personalizado
    win_copy:
      src: arqs/index.html
      dest: "C:\\inetpub\\wwwroot\\index.html"
